### ISSUE TITLE
Customer: edit my cart if I change my mind: change the quantity of a product in my cart. remove a product in my cart. No one else should be able to edit my cart except me.

### ISSUE THREAD

**Issue by KristinLevine** [2206-fsa-ghp-taurus/grace-shopper#7]

**Comment by yaoyaodebbie97** [comment]
Everything else works, just need to check "no one else should be able to edit my cart except me' 
Maybe we can just test in postman - check that we are not able to post to /api/cart??

**Comment by KristinLevine** [comment]
Ask Chris is security used fulfills requirement.
