### ISSUE TITLE
Customer: "checkout" the items in my cart so I can purchase my desired goods.

### ISSUE THREAD

**Issue by KristinLevine** [2206-fsa-ghp-taurus/grace-shopper#8]

**Comment by yaoyaodebbie97** [comment]
1. How to store guest’s order information (it is not going to database now, so we don’t have an order id) (Just from a presentation perspective, it doesn’t matter whether we save it or not as we are not going to show the database? )

2. How to close the order when user click on checkout (mark the status from open to close)
My thought is when check out - - in the backend, we just update the order from open to close (if it is a guest, we can also just create an order with the status of close)

My thought is when check out - - in the backend, we just update the order from open to close (if it is a guest, we can also just create an order with the status of close)
